version: '3.4'
networks:
  microsservices-network:
    driver: bridge
services:
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microsservices-network    
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672 
    ports:
      - 9411:9411
    networks:
      - microsservices-network
    depends_on:
      - rabbit-mq     
  naming-server:
    image: jonviegas/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - microsservices-network
  api-gateway:
    image: jonviegas/api-gateway:0.0.1-SNAPSHOT
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8765:8765  
    depends_on:
      - naming-server  
      - rabbit-mq
    networks:
      - microsservices-network
  conversion-service:
    image: jonviegas/conversion-service:0.0.1-SNAPSHOT
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit    
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - conversion-db
      - rabbit-mq
    networks:
      - microsservices-network
  book-service:
    image: jonviegas/book-service:0.0.1-SNAPSHOT
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit    
    restart: always
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq 
    networks:
      - microsservices-network     
  conversion-db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: conversion_service
      MYSQL_ROOT_HOST: '%'          
    ports:
      - 3308:3306
    networks:
      - microsservices-network      
  book-db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'          
    ports:
      - 3309:3306 
    networks:
      - microsservices-network
