server:
  port: 8765
spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: conversion-service
          uri: lb://conversion-service
          predicates:
            - Path=/conversion/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: openapi
          uri: lb://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  profiles:
    active:
    - prod
  
