eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://conversion-db/conversion_service?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    url: jdbc:mysql://conversion-db/
    schemas: conversion_service
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  zipkin:
    base-url: http://zipkin:9411/
