eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conversion_service?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: conversion_service
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
