eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://book-db/book_service?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    url: jdbc:mysql://book-db/
    schemas: book_service
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  zipkin:
    base-url: http://zipkin:9411/
